FROM node:18-alpine3.15

WORKDIR /app

# COPY package.json and package-lock.json files
COPY package*.json /app/

#Install package.json dependencies.
RUN npm install

#Copy dir content
COPY . .


#Generate Prisma client.
RUN npx prisma generate

EXPOSE 9000

CMD ["npm", "run", "dev"]